# Generated by Django 4.2.13 on 2026-07-19 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0012_product_fm_products_categor_8af6ad_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('highlight_title', models.CharField(blank=True, help_text='Green/coloured first word(s) in the hero headline.', max_length=100, null=True)),
                ('highlight_color', models.CharField(default='#4ade80', help_text='CSS colour for highlight_title (hex or named).', max_length=20)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(blank=True, help_text='Body paragraph shown below the subtitle.', max_length=500)),
                ('image', models.ImageField(upload_to='banners/')),
                ('cta_text', models.CharField(blank=True, default='Shop Now', max_length=100)),
                ('cta_link', models.CharField(blank=True, help_text='Relative path or full URL for the CTA button.', max_length=300)),
                ('placement', models.CharField(choices=[('hero', 'Hero — Homepage top slider'), ('promo', 'Promo — Discount & Product Offer banner'), ('top_offers', 'Top Offers — Grid section'), ('popup', 'Popup Banner')], default='hero', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'fm_banners',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop_categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'db_table': 'fm_shop_categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PopularCategoryPill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Emoji icon shown before the label e.g. 🥦', max_length=10)),
                ('custom_path', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'db_table': 'fm_popular_pills',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Auto-populate from title. Used to build the default /listing?category= URL.', max_length=120, unique=True)),
                ('custom_path', models.CharField(blank=True, help_text='Override URL (e.g. /deals or /listing?tag=new). Takes priority over category.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory')),
            ],
            options={
                'verbose_name': 'Nav Menu (Top Bar)',
                'verbose_name_plural': 'Nav Menus (Top Bar)',
                'db_table': 'fm_nav_menus',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NavCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, help_text='Square icon image shown in the dropdown (64×64 px recommended).', null=True, upload_to='nav_icons/')),
                ('icon_emoji', models.CharField(blank=True, help_text='Fallback emoji if no image icon is uploaded (e.g. 🥦).', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Green sub-text with item examples (e.g. Rice, Oils, Dals).')),
                ('custom_path', models.CharField(blank=True, help_text='Override URL if this entry should not follow the category slug.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nav_category_entries', to='products.category')),
                ('parent', models.ForeignKey(blank=True, help_text='Leave blank for top-level entries.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.navcategory')),
            ],
            options={
                'verbose_name': 'Nav Category (Dropdown)',
                'verbose_name_plural': 'Nav Categories (Dropdown)',
                'db_table': 'fm_nav_categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FruitsVegetableCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='card_sections/')),
                ('badge', models.CharField(blank=True, help_text='Short label shown on the card, e.g. "MIN 27% OFF" or "NEW".', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory')),
            ],
            options={
                'verbose_name': 'Fruits & Vegetable Card',
                'verbose_name_plural': 'Fruits & Vegetable Cards',
                'db_table': 'fm_fruits_vegetable_cards',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeaturedSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='featured/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory')),
            ],
            options={
                'db_table': 'fm_featured_sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DailyDealCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='card_sections/')),
                ('badge', models.CharField(blank=True, help_text='Short label shown on the card, e.g. "MIN 27% OFF" or "NEW".', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, help_text='Optional longer description shown beneath the subtitle on the card.')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.subcategory')),
            ],
            options={
                'verbose_name': 'Daily Deal Card',
                'verbose_name_plural': 'Daily Deal Cards',
                'db_table': 'fm_daily_deal_cards',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
