# Generated by Django 4.2.13 on 2026-08-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_banner_image_alter_dailydealcard_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AddField(
            model_name='dailydealcard',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AddField(
            model_name='featuredsection',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AddField(
            model_name='fruitsvegetablecard',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AddField(
            model_name='navcategory',
            name='icon_file',
            field=models.ImageField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='temp/'),
        ),
    ]
