# Generated by Django 4.2.13 on 2026-08-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_banner_image_file_dailydealcard_image_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navcategory',
            name='icon_file',
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='dailydealcard',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailydealcard',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='card_sections/'),
        ),
        migrations.AlterField(
            model_name='featuredsection',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='featuredsection',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='featured/'),
        ),
        migrations.AlterField(
            model_name='fruitsvegetablecard',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fruitsvegetablecard',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='card_sections/'),
        ),
        migrations.AlterField(
            model_name='navcategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='nav_icons/'),
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='shop_categories/'),
        ),
    ]
