# Generated by Django 4.2.13 on 2026-06-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Site', max_length=100)),
                ('default_avatar', models.ImageField(blank=True, null=True, upload_to='defaults/')),
            ],
            options={
                'db_table': 'fm_site_settings',
            },
        ),
    ]
