# Generated by Django 4.2.13 on 2026-06-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_hover',
            field=models.BooleanField(default=False, help_text='Shown in the product card when the primary image is hovered (imgB). Leave unset to auto-pick the next uploaded image.'),
        ),
    ]
