# Generated by Django 4.2.13 on 2026-06-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_is_hover'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Controls display order across admin list, home page, and listing page (lower numbers appear first). Products sharing the same value fall back to newest-first.'),
        ),
    ]
