# Generated by Django 4.2.13 on 2026-06-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', '-created_at']},
        ),
    ]
