# Generated by Django 4.2.13 on 2026-06-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_category_alter_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_best_selling',
            field=models.BooleanField(default=False),
        ),
    ]
