# Generated by Django 4.2.13 on 2026-06-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_subcategory_is_best_selling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='is_best_selling',
        ),
        migrations.AddField(
            model_name='product',
            name='is_best_selling',
            field=models.BooleanField(default=False),
        ),
    ]
