# Generated by Django 4.2.13 on 2026-06-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_subcategory_is_best_selling_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'category'], name='fm_products_is_acti_fb4d69_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_best_selling'], name='fm_products_is_best_c7dcbe_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='fm_products_is_feat_771735_idx'),
        ),
    ]
