# Generated by Django 4.2.13 on 2026-07-11 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_fm_products_is_acti_fb4d69_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='fm_products_is_acti_fb4d69_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='fm_products_is_best_c7dcbe_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='fm_products_is_feat_771735_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_best_selling',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Optional — narrows the product to a specific subcategory under its Category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.subcategory'),
        ),
    ]
