# Generated by Django 4.2.13 on 2026-07-12 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_fm_products_is_acti_fb4d69_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Sub-Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_best_selling',
            field=models.BooleanField(default=False, help_text='Show in Best Selling section on homepage.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, help_text='Short promotional label shown on card e.g. "41% OFF", "NEW".', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in Featured Offers section and Smart Basket on homepage.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in homepage sections and listing page.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.JSONField(blank=True, default=dict, help_text='Key-value product specifications shown on detail page.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Optional sub-level classification within the category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.subcategory'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_hover',
            field=models.BooleanField(default=False, help_text='Hover/rollover image on card (imgB). Only one image per product should be hover.'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Main card image (imgA). Only one image per product should be primary.'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='delivery_mins',
            field=models.PositiveIntegerField(default=10, help_text='Estimated delivery in minutes'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='mrp',
            field=models.DecimalField(decimal_places=2, help_text='Maximum retail price in ₹', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price in ₹', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='weight',
            field=models.CharField(help_text='e.g. "1 kg", "500 gm", "80g pack"', max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon e.g. 🥦', max_length=10),
        ),
    ]
