# Generated by Django 4.2.13 on 2026-07-20 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_fm_products_categor_8af6ad_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Label shown in uppercase (e.g. "ORIGIN", "SHELF LIFE").', max_length=100)),
                ('value', models.CharField(help_text='Value for this specification (e.g. "Local Orchards").', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Specification',
                'verbose_name_plural': 'Product Specifications',
                'db_table': 'fm_product_specifications',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_title', models.CharField(blank=True, help_text='H2 title shown above the "About the product" box. Usually the brand + product name (e.g. "Fresho! Capsicum - Green"). Falls back to product.name when left blank.', max_length=300)),
                ('body', models.TextField(help_text='Full "About the product" paragraph body text.')),
                ('recipe_url', models.URLField(blank=True, help_text='Optional recipe link shown at the end of the about section.')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_description', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Description',
                'verbose_name_plural': 'Product Descriptions',
                'db_table': 'fm_product_descriptions',
            },
        ),
    ]
